---
- name: check installation status 
  stat: 
    path: '~/.oh-my-zsh'
  become_user: '{{ ansible_user_id }}'
  register: p

- name: Get oh my zsh file
  get_url: "url={{ oh_my_zsh_url }} dest=/tmp/{{ file_name }} mode=0755"
  when: p.stat.isdir is not defined 

- name: Install oh my zsh
  shell: "/tmp/{{ file_name }}"
  when: p.stat.isdir is not defined 
  become_user: '{{ ansible_user_id }}'

- name: Swtich default shell 
  command: 'chsh -s /usr/local/bin/zsh'

- name: Check installation status for fzf
  stat: 
    path: '~/.fzf'
  become_user: '{{ ansible_user_id }}'
  register: fzf

- name: Clone fzf 
  git: 
    repo: "https://github.com/junegunn/fzf.git"
    dest: "~/.fzf"
  become_user: '{{ ansible_user_id }}'
  # when: fzf.stat.isdir is not defined

- name: Install fzf
  shell: "~/.fzf/install"
  become_user: "{{ ansible_user_id }}"
  # when: fzf.stat.isdir is not defined
  
