--- 
  - hosts: all
    vars_files: 
      - vars/main.yml

    roles: 
      - alan2112000.homebrew
      - alan2112000.dotfiles
      - role: rvm_io.ruby
        tags: ruby
        rvm1_rubies: ['ruby-2.2.2', 'ruby-2.3.3']
        rvm1_user: "{{ ansible_user_id }}"
