---
homebrew_repo: https://github.com/Homebrew/brew

homebrew_prefix: /usr/local
homebrew_install_path: "{{ homebrew_prefix }}/Homebrew"
homebrew_brew_bin_path: /usr/local/bin

homebrew_installed_packages:
  - ssh-copy-id
  - pv

homebrew_uninstalled_packages: []

homebrew_upgrade_all_packages: no

homebrew_taps:
  - homebrew/core
  - caskroom/cask

homebrew_cask_apps:
  - firefox

homebrew_cask_appdir: /Applications

homebrew_use_brewfile: true
homebrew_brewfile_dir: '~'
oh_my_zsh_url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
file_name: 'oh_my_zsh_install.sh'
